MvcOnlineTicariOtomasyon/Controllers/FaturaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcOnlineTicariOtomasyon.Models.Siniflar;


namespace MvcOnlineTicariOtomasyon.Controllers
{
    public class FaturaController : Controller
    {
        // GET: Fatura
        Context c = new Context();
        public ActionResult Index()
        {
            var liste = c.Faturalars.ToList();
            return View(liste);
        }
         [HttpGet]
        public ActionResult FaturaEkle()
        {
            return View();
        }
        [HttpPost]
        public ActionResult FaturaEkle(Faturalar f)
        {
            c.Faturalars.Add(f);
            c.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult FaturaGetir(int id)
        {
            var fatura = c.Faturalars.Find(id);
            return View("FaturaGetir", fatura);
        }

        public ActionResult FaturaGuncelle(Faturalar f)
        {
            var fatura = c.Faturalars.Find(f.Faturaİd);

            fatura.FaturaSeriNo = f.FaturaSeriNo;
            fatura.FaturaSıraNo = f.FaturaSıraNo;
            fatura.Tarih = f.Tarih;
            fatura.VergiDairesi = f.VergiDairesi;
            fatura.Saat= f.Saat;
            fatura.TeslimAlan= f.TeslimAlan;
            fatura.TeslimEden= f.TeslimEden;
          
            c.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult FaturaListesi()
        {
            var faturalar = c.Faturalars.ToList();
            return View(faturalar);
        }

        public ActionResult FaturaDetay(int id)
        {
            var kalemler = c.FaturaKalems.Where(x => x.Faturaid == id).ToList();

            return View(kalemler);

        }

        [HttpGet]
        public ActionResult YeniKalem()
        {
            return View();
        }
        [HttpPost]
        public ActionResult YeniKalem(FaturaKalem f)
        {
            c.FaturaKalems.Add(f);
            c.SaveChanges();
            return RedirectToAction("Index");
        }
    }

}

MvcOnlineTicariOtomasyon/Views/Fatura/FaturaDetay.cshtml
@using MvcOnlineTicariOtomasyon.Models.Siniflar
@model List<FaturaKalem>
@{
    ViewBag.Title = "FaturaDetay";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<h2 class="mx-4">Fatura Kalemleri Sayfası</h2>

<ol class="breadcrumb mb-4">
    <li class="breadcrumb-item active">Fatura Kalem Detayları</li>
</ol>
<table class="table table-hover">
    <tr>
        <th>Fatura Kalem ID</th>
        <th>Açıklama</th>
        <th>Miktar</th>
        <th>Birim Fiyat</th>
        <th>Tutar</th>
    </tr>
    @foreach (var m in Model)
    {
        <tr>
            <th>@m.FaturaKalemİd</th>
            <th>@m.Aciklama</th>
            <th>@m.Miktar</th>
            <th>@m.BirimFiyat</th>
            <th>@m.Tutar</th>
        </tr>
}
</table>

<th><a href="/Fatura/YeniKalem" class="btn btn-primary"><i class="fa fa-plus"></i> Yeni Kalem Ekle</a></th>

MvcOnlineTicariOtomasyon/Views/Fatura/FaturaEkle.cshtml
@model MvcOnlineTicariOtomasyon.Models.Siniflar.Faturalar
@{
    ViewBag.Title = "FaturaEkle";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<h2>Yeni Fatura Ekleme Sayfası</h2>
<br />

<form class="mx-4" action="/Fatura/FaturaEkle" method="post"  >
    @Html.LabelFor(x => x.FaturaSeriNo)
    @Html.TextBoxFor(x => x.FaturaSeriNo, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.FaturaSıraNo)
    @Html.TextBoxFor(x => x.FaturaSıraNo, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.Tarih)
    @Html.TextBoxFor(x => x.Tarih, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.VergiDairesi)
    @Html.TextBoxFor(x => x.VergiDairesi, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.Saat)
    @Html.TextBoxFor(x => x.Saat, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.TeslimAlan)
    @Html.TextBoxFor(x => x.TeslimAlan, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.TeslimEden)
    @Html.TextBoxFor(x => x.TeslimEden, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.Toplam)
    @Html.TextBoxFor(x => x.Toplam, new { @class = "form-control" })
    <br />

    <button class="btn btn-info">Ekle</button>
</form>

MvcOnlineTicariOtomasyon/Views/Fatura/FaturaGetir.cshtml
@model MvcOnlineTicariOtomasyon.Models.Siniflar.Faturalar
@{
    ViewBag.Title = "FaturaGetir";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<h2 class="mx-4">Fatura Güncelleme Sayfası</h2>

@using (Html.BeginForm("FaturaGuncelle", "Fatura", FormMethod.Post))
{
<div class="form-group" >
    @Html.LabelFor(x => x.FaturaSeriNo)
    @Html.TextBoxFor(x => x.FaturaSeriNo, new { @class = "form-control" })

    @Html.LabelFor(x => x.FaturaSıraNo)
    @Html.TextBoxFor(x => x.FaturaSıraNo, new { @class = "form-control" })

    @Html.LabelFor(x => x.VergiDairesi)
    @Html.TextBoxFor(x => x.VergiDairesi, new { @class = "form-control" })

    @Html.LabelFor(x => x.Tarih)
    @Html.TextBoxFor(x => x.Tarih, new { @class = "form-control" })


    @Html.LabelFor(x => x.Saat)
    @Html.TextBoxFor(x => x.Saat, new { @class = "form-control" })

    @Html.LabelFor(x => x.TeslimAlan)
    @Html.TextBoxFor(x => x.TeslimAlan, new { @class = "form-control" })

    @Html.LabelFor(x => x.TeslimEden)
    @Html.TextBoxFor(x => x.TeslimEden, new { @class = "form-control" })

    @Html.LabelFor(x => x.Toplam)
    @Html.TextBoxFor(x => x.Toplam, new { @class = "form-control" })

    @Html.HiddenFor(x => x.Faturaİd)

</div>
                <button class="btn btn-info">Güncelle</button>}

MvcOnlineTicariOtomasyon/Views/Fatura/FaturaKalemEkle.cshtml
@model MvcOnlineTicariOtomasyon.Models.Siniflar.FaturaKalem
@{
    ViewBag.Title = "FaturaKalemEkle";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<h2>Fatura Kalem Ekleme Sayfası</h2>


<form class="form-group" action="/Fatura/FaturaKalemEkle" method="post">
    @Html.LabelFor(x => x.Miktar)
    @Html.TextBoxFor(x => x.Miktar, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.BirimFiyat)
    @Html.TextBoxFor(x => x.BirimFiyat, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.Tutar)
    @Html.TextBoxFor(x => x.Tutar, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.Aciklama)
    @Html.TextBoxFor(x => x.Aciklama, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.Faturaid)
    @Html.TextBoxFor(x => x.Faturaid , new { @class = "form-control" })
    <br />

    <button class="btn btn-info"><i class="fa fa-plus"></i> Ekle</button>

</form>

MvcOnlineTicariOtomasyon/Views/Fatura/Index.cshtml
@using MvcOnlineTicariOtomasyon.Models.Siniflar
@model List<Faturalar>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<h2 class="mx-4">Faturalar</h2>
<br />

<table id="tbl1" class="table table-bordered" >
    <thead class="mx-lg-5">
        <tr>
            <th>Fatura ID</th>
            <th>Seri No</th>
            <th>Sıra No</th>
            <th>Tarih</th>
            <th>Saat</th>
            <th>Vergi Dairesi</th>
            <th>Teslim Alan</th>
            <th>Teslim Eden</th>
            <th>Toplam</th>
            <th>İşlemler</th>
        </tr>
    </thead>
    @foreach (var m in Model)
    {
<tr>

    <td>@m.Faturaİd</td>
    <td>@m.FaturaSeriNo</td>
    <td>@m.FaturaSıraNo</td>
    <td>@m.Tarih</td>
    <td>@m.Saat</td>
    <td>@m.VergiDairesi</td>
    <td>@m.TeslimAlan</td>
    <td>@m.TeslimEden</td>
    <td>@m.Toplam</td>



    <td>
        <a href="/Fatura/FaturaGetir/@m.Faturaİd" class="btn btn-warning"><i class="fa fa-undo"></i> Güncelle</a>
        <a href="/Fatura/FaturaDetay/@m.Faturaİd" class="btn btn-info"><i class="fa fa-info"></i> Detaylar</a>
    </td>
</tr>}
</table>
<br />
<br />

<a href="/Fatura/FaturaEkle" class="btn btn-primary"><i class="fa fa-plus"></i> Yeni Fatura Ekle</a>
<a href="/Fatura/FaturaListesi" class="btn btn-info"><i class="fa fa-print"></i> Yazdır</a>

<link rel="stylesheet" type="text/css" href="http://ajax.aspnetcdn.com/ajax/jquery.dataTables/1.9.4/css/jquery.dataTables.css">

<script type="text/javascript" charset="utf8" src="http://ajax.aspnetcdn.com/ajax/jQuery/jquery-1.8.2.min.js"></script>
<script type="text/javascript" charset="utf8" src="http://ajax.aspnetcdn.com/ajax/jquery.dataTables/1.9.4/jquery.dataTables.min.js"></script>

<script>$('#tbl1').dataTable({});</script>

MvcOnlineTicariOtomasyon/Views/Fatura/YeniKalem.cshtml
@model MvcOnlineTicariOtomasyon.Models.Siniflar.FaturaKalem
@{
    ViewBag.Title = "YeniKalem";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<h2>Fatura Kalem Ekleme Sayfası</h2>


<form class="mx-2" action="/Fatura/YeniKalem" method="post">
    @Html.LabelFor(x => x.Miktar)
    @Html.TextBoxFor(x => x.Miktar, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.BirimFiyat)
    @Html.TextBoxFor(x => x.BirimFiyat, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.Tutar)
    @Html.TextBoxFor(x => x.Tutar, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.Aciklama)
    @Html.TextBoxFor(x => x.Aciklama, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.Faturaid)
    @Html.TextBoxFor(x => x.Faturaid, new { @class = "form-control" })
    <br />

    <button class="btn btn-info"><i class="fa fa-plus"></i> Ekle</button>

</form>