MvcOnlineTicariOtomasyon/Controllers/SatisController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcOnlineTicariOtomasyon.Models.Siniflar;

namespace MvcOnlineTicariOtomasyon.Controllers
{
    public class SatisController : Controller
    {
        // GET: Satis
        Context c = new Context();  
        public ActionResult Index()
        {
            
            var degerler = c.SatisHarekets.ToList();
            return View(degerler);
        }
        [HttpGet]
        public ActionResult YeniSatis()
        {
            List<SelectListItem> deger1 = (from x in c.Uruns.ToList()
                                           select new SelectListItem
                                           {
                                               Text = x.UrunAd,
                                               Value = x.UrunId.ToString()

                                           }).ToList();
            List<SelectListItem> deger2 = (from x in c.Carilers.ToList()
                                           select new SelectListItem
                                           {
                                               Text = x.CariAd +" "+  x.CariSoyad,
                                               Value = x.Cariid.ToString()

                                           }).ToList();
            List<SelectListItem> deger3 = (from x in c.Personels.ToList()
                                           select new SelectListItem
                                           {
                                               Text = x.PersonelAd +" "+ x.PersonelSoyad,
                                               Value = x.PersonelId.ToString()

                                           }).ToList();
            ViewBag.dgr1 = deger1;
            ViewBag.dgr2 = deger2;
            ViewBag.dgr3 = deger3;
                return View();

        }
        [HttpPost]
        public ActionResult YeniSatis(SatisHareket s)
        {
            s.Tarih = DateTime.Parse(DateTime.Now.ToShortDateString());
            c.SatisHarekets.Add(s);
            c.SaveChanges();
            return RedirectToAction("Index");

        }
        public ActionResult SatisGetir(int id)
        {
            var satis = c.SatisHarekets.Find(id);

            List<SelectListItem> urunler = (from x in c.Uruns.ToList()
                                            select new SelectListItem
                                            {
                                                Text = x.UrunAd,
                                                Value = x.UrunId.ToString()
                                            }).ToList();
            List<SelectListItem> cariler = (from x in c.Carilers.ToList()
                                            select new SelectListItem
                                            {
                                                Text = x.CariAd + " " + x.CariSoyad,
                                                Value = x.Cariid.ToString()
                                            }).ToList();
            List<SelectListItem> personeller = (from x in c.Personels.ToList()
                                                select new SelectListItem
                                                {
                                                    Text = x.PersonelAd + " " + x.PersonelSoyad,
                                                    Value = x.PersonelId.ToString()
                                                }).ToList();
            ViewBag.urun = urunler;
            ViewBag.cari = cariler;
            ViewBag.personel = personeller;


            return View("SatisGetir", satis);
        }
        public ActionResult SatisGuncelle(SatisHareket s)
        {
            var sts = c.SatisHarekets.Find(s.Satisİd);

            sts.Cariid = s.Cariid;
            sts.Personelid = s.Personelid;
            sts.Urunid = s.Urunid;
            sts.Adet = s.Adet;
            sts.Fiyat = s.Fiyat;
            sts.ToplamTutar = s.ToplamTutar;

            c.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult SatisDetay(int id)
        {
            var degerler = c.SatisHarekets.Where(x => x.Satisİd == id).ToList();
            return View(degerler);
        }

        public ActionResult SatisListesi()
        {
            var satislar = c.SatisHarekets.ToList();
            return View(satislar);
        }
    }
}

MvcOnlineTicariOtomasyon/Views/Satis/Index.cshtml
@using MvcOnlineTicariOtomasyon.Models.Siniflar
@model  List<SatisHareket>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<h2 style="margin-top:20px">SATIŞLAR</h2>

<table id="tbl1" class="table table-hover" cellspacing="0" width="100%">
    <thead>
        <tr>
            <th>#</th>
            <th>Ürün</th>
            <th>Cari</th>
            <th>Personel</th>
            <th>Adet</th>
            <th>Fiyat</th>
            <th>Toplam Tutar</th>
            <th>Tarih</th>
            <th>İşlemler</th>
        </tr>
    </thead>
    @foreach (var k in Model)
    {
        <tr>

            <td>  @k.Satisİd</td>
            <td>  @k.Urun.UrunAd </td>
            <td>  @k.Cariler.CariAd @k.Cariler.CariSoyad </td>
            <td>  @k.Personel.PersonelAd @k.Personel.PersonelSoyad </td>
            <td>  @k.Adet </td>
            <td>  @k.Fiyat </td>
            <td>  @k.ToplamTutar </td>
            <td>  @k.Tarih </td>

            <td>
                <a href="/Satis/SatisGetir/@k.Satisİd" class="btn btn-warning"><i class="fa fa-undo"></i> Güncelle</a>
                <a href="/Satis/SatisDetay/@k.Satisİd" class="btn btn-info"><i class="fa fa-info-circle"></i> Detay</a>
            </td>


        </tr>


    }


</table>
<a href="/Satis/YeniSatis" class="btn btn-info">Yeni Satış Yap</a>

MvcOnlineTicariOtomasyon/Views/Satis/SatisDetay.cshtml
@using MvcOnlineTicariOtomasyon.Models.Siniflar
@model List<SatisHareket>

@{ ViewBag.Title = "SatisDetay";
                Layout = "~/Views/Shared/AdminLayout.cshtml"; }

<h2>SatisDetay</h2>
<br />

<table class="table table-hover">
    <tr>
        <th>#</th>
        <th>Cari</th>
        <th>Personel</th>
        <th>Ürün</th>
        <th>Adet</th>
        <th>Fiyat</th>
        <th>Toplam Tutar</th>
        <th>Tarih</th>

    </tr>
    @foreach (var x in Model)
    {
<tr>
    <td>@x.Satisİd</td>
    <td>@x.Urun.UrunAd</td>
    <td>@x.Cariler.CariAd @x.Cariler.CariSoyad</td>
    <td>@x.Personel.PersonelAd @x.Personel.PersonelSoyad</td>
    <td>@x.Fiyat</td>
    <td>@x.Adet</td>
    <td>@x.ToplamTutar</td>
    <td>@x.Tarih.ToShortDateString()</td>
</tr>}
</table>
<button class="btn-default" style="background-color:dodgerblue">Yazdır</button>

MvcOnlineTicariOtomasyon/Views/Satis/SatisGetir.cshtml
@model MvcOnlineTicariOtomasyon.Models.Siniflar.SatisHareket
@{
    ViewBag.Title = "SatisGetir";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<h2>Satış Güncelleme Sayfası</h2>

@using (Html.BeginForm("SatisGuncelle", "Satis", FormMethod.Post))
{
    @Html.Label("Cari:")
    @Html.DropDownListFor(x => x.Cariid, (List<SelectListItem>)ViewBag.cari, new { @class = "form-control" })
    <br />
    @Html.Label("Personel:")
    @Html.DropDownListFor(x => x.Personelid, (List<SelectListItem>)ViewBag.personel, new { @class = "form-control" })
    <br />
    @Html.Label("Urun:")
    @Html.DropDownListFor(x => x.Urunid, (List<SelectListItem>)ViewBag.urun, new { @class = "form-control" })
    <br />
    @Html.Label("Adet:")
    @Html.TextBoxFor(x => x.Adet, new { @class = "form-control" })
    <br />
    @Html.Label("Fiyat:")
    @Html.TextBoxFor(x => x.Fiyat, new { @class = "form-control" })
    <br />
    @Html.Label("Toplam Tutar:")
    @Html.TextBoxFor(x => x.ToplamTutar, new { @class = "form-control" })
    @Html.HiddenFor(x => x.Satisİd)

    <br />
    <button class="btn btn-info"><i class="fa fa-undo"></i> Güncelle</button>
}

MvcOnlineTicariOtomasyon/Views/Satis/YeniSatis.cshtml
@model MvcOnlineTicariOtomasyon.Models.Siniflar.SatisHareket
@{
    ViewBag.Title = "YeniSatis";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<br />
<h2 class="mx-4"> Yeni Ürün Sayfası</h2>
<br />
<form class="form-group mx-4" method="post">
    @Html.LabelFor(x => x.Urun)
    @Html.DropDownListFor(x => x.Urunid
, (List<SelectListItem>)ViewBag.dgr1, new { @class = "form-control" })
    @*@Html.TextBoxFor(x => x.Kategoriid, new { @class = "form-control" })*@
    <br />
    @Html.Label("Cari")
    @Html.DropDownListFor(x => x.Cariid
, (List<SelectListItem>)ViewBag.dgr2, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.Personel)
    @Html.DropDownListFor(x => x.Personelid

, (List<SelectListItem>)ViewBag.dgr3, new { @class = "form-control" })
    <br />

    @Html.LabelFor(x => x.Adet)
    @Html.TextBoxFor(x => x.Adet, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.Fiyat)
    @Html.TextBoxFor(x => x.Fiyat, new { @class = "form-control" })
    <br />

    <br />
    @Html.LabelFor(x => x.ToplamTutar)
    @Html.TextBoxFor(x => x.ToplamTutar, new { @class = "form-control" })
    <br />

    <button class="btn btn-info">Satışı Tamamla</button>

</form>